it = twice_iter([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print ("use for iteration")
for i in it:
    print(i)
print("next(it)")
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))